### ISSUE TITLE
usonic.js 5:14 Exception

### ISSUE THREAD

**Issue by kodejak** [mochman/mmm-usonic#1]
Hello mochman,
I want to use your code in my Magic Mirror and had an issue.

> Error: Module version mismatch. Expected 50, got 48.
>     at Error (native)
>     at process.module.(anonymous function) [as dlopen](ELECTRON_ASAR.js:168:20)
>     at Object.Module._extensions..node (module.js:583:18)
>     at Object.module.(anonymous function) [as .node](ELECTRON_ASAR.js:168:20)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
>     at Module.require (module.js:483:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Swipe/node_modules/mmm-usonic/lib/usonic.js:5:14)
> Whoops! There was an uncaught exception...
> Error: Module version mismatch. Expected 50, got 48.
>     at Error (native)
>     at process.module.(anonymous function) [as dlopen](ELECTRON_ASAR.js:168:20)
>     at Object.Module._extensions..node (module.js:583:18)
>     at Object.module.(anonymous function) [as .node](ELECTRON_ASAR.js:168:20)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
>     at Module.require (module.js:483:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Swipe/node_modules/mmm-usonic/lib/usonic.js:5:14)
> MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
> If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
> Launching application.

The message says that there is a problem in usonic.js. It's this line:
`var usonic = require('../build/Release/usonic.node');`

Cheers,
Christian

**Comment by mochman** [comment]
Christian,

I've seen other users having the same error.  I am not able to reproduce it on my end.  I've fully removed the MMM-Swipe folder and re cloned it then ran `npm install`.  I was then able to load the module without those errors.

I'm running it on a Raspi 3
NodeJs 6.7.0
Fully updated with

```
sudo apt-get update
sudo apt-get dist-upgrade
sudo rpi-update
```

I just removed the entire MMM-Swipe Folder

```
cd ~/MagicMirror/modules/
git clone https://github.com/mochman/MMM-Swipe
cd MMM-Swipe/
npm install
cd ~/MagicMirror/
sudo npm start
```

**Comment by mochman** [comment]
@kodejak I updated the MMM-Swipe package.json file to fix this issue.  Please remove your node_helper folder, git pull the new file and try installing it again.
